In [1]:
import numpy as np
import pandas as pd

In [2]:
x1 = np.random.uniform(0,1,20000)
x2 = np.random.uniform(0,1,20000)
x3 = np.random.uniform(0,1,20000)
x4 = np.random.uniform(0,1,20000)
x5 = np.random.uniform(0,1,20000)
x6 = np.random.uniform(0,1,20000)
x7 = np.random.uniform(0,1,20000)
x8 = np.random.uniform(0,1,20000)
x9 = np.random.uniform(0,1,20000)
x10= np.random.uniform(0,1,20000)

In [3]:
data = pd.DataFrame([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10]).transpose()
data.columns = ['x1','x2','x3','x4','x5','x6','x7','x8','x9','x10']

### Create Drifts
All drifts are gradual.

1. Drift @ [5000:7500]: x1, x3 and x5 are now np.random.uniform(-1,2,2500) and y from y_org to y_1
2. Drift @ [7500:10000]: x1, x3 and x5 are now np.random.uniform(-1,2,2500) and y from y_1 to y_2
3. Drift @ [15000:17500]: y from y_org to y_1
4. Drift @ [17500:20000]: y from y_1 to y_2

In [5]:
data['x1'][5000:10000]=np.random.uniform(-1,2,5000)
data['x3'][5000:10000]=np.random.uniform(-1,2,5000)
data['x5'][5000:10000]=np.random.uniform(-1,2,5000)

In [6]:
data['y_org'] = 10*np.sin(np.pi*data['x1']*data['x2'])+20*(data['x3']-0.5)**2 + 10*data['x4'] + 5*data['x5'] + np.random.normal(0,1)
data['y_1'] = 10*np.sin(np.pi*data['x4']*data['x5'])+20*(data['x2']-0.5)**2 + 10*data['x1'] + 5*data['x3'] + np.random.normal(0,1)
data['y_2'] = 10*np.sin(np.pi*data['x2']*data['x5'])+20*(data['x4']-0.5)**2 + 10*data['x3'] + 5*data['x1'] + np.random.normal(0,1)

In [7]:
data['y_global_gradual'] = data['y_org']

prob = 0.05
for i in range(5001,6000):
    p = np.random.binomial(1, prob)
    
    if p > 0:
        data['y_global_gradual'][i] = data['y_1'][i]
        
    if (i%100) == 0:
        prob += 0.1
        
data['y_global_gradual'][6000:7500] = data['y_1'][6000:7500]

prob = 0.05
for i in range(7501,8500):
    p = np.random.binomial(1, prob)
    
    if p > 0:
        data['y_global_gradual'][i] = data['y_2'][i]
        
    if (i%100) == 0:
        prob += 0.1
        
data['y_global_gradual'][8500:] = data['y_2'][8500:]

In [8]:
prob = 0.05
for i in range(15001,16000):
    p = np.random.binomial(1, prob)
    
    if p > 0:
        data['y_global_gradual'][i] = data['y_1'][i]
        
    if (i%100) == 0:
        prob += 0.1
        
data['y_global_gradual'][16000:17500] = data['y_1'][6000:7500]

prob = 0.05
for i in range(17501,18500):
    p = np.random.binomial(1, prob)
    
    if p > 0:
        data['y_global_gradual'][i] = data['y_2'][i]
        
    if (i%100) == 0:
        prob += 0.1
        
data['y_global_gradual'][18500:] = data['y_2'][18500:]

In [9]:
data

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y_org,y_1,y_2,y_global_gradual
0,0.012774,0.995605,0.604646,0.261849,0.347732,0.376647,0.840638,0.033230,0.836744,0.082162,4.193662,11.209680,17.896143,4.193662
1,0.693830,0.242294,0.205597,0.301411,0.260596,0.615274,0.281280,0.192797,0.499371,0.025796,10.307848,12.061724,10.080715,10.307848
2,0.320461,0.010298,0.909705,0.427100,0.103176,0.713575,0.639295,0.480550,0.041480,0.538457,7.465784,14.253818,12.635218,7.465784
3,0.397825,0.658220,0.844503,0.902887,0.106007,0.974693,0.101608,0.252041,0.648181,0.869212,18.480089,11.987752,17.651265,18.480089
4,0.236447,0.105775,0.484184,0.865344,0.894382,0.878050,0.855222,0.180417,0.334742,0.611914,13.133316,14.737794,13.418273,13.133316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0.164622,0.398669,0.164564,0.877826,0.193433,0.294068,0.997194,0.046414,0.433770,0.585950,13.261067,8.083963,9.519024,9.519024
19996,0.058901,0.723534,0.083488,0.174423,0.222037,0.691175,0.313284,0.098554,0.584657,0.464378,6.876986,3.544032,9.881044,9.881044
19997,0.977838,0.837940,0.030700,0.428534,0.274042,0.372221,0.133364,0.548207,0.455003,0.014437,14.653415,16.146743,13.698950,13.698950
19998,0.770219,0.414065,0.255964,0.184291,0.771604,0.356440,0.052232,0.789105,0.107153,0.813439,14.535120,13.774469,18.635130,18.635130
19999,0.322734,0.464192,0.314246,0.968607,0.145538,0.453111,0.054980,0.727606,0.344913,0.537909,14.856502,9.434064,13.050644,13.050644

In [10]:
data.to_csv('friedman_with_4_gradual_drift.csv', index=False)